"""
Tests for videogen/render.py — EDL-driven renderer.

Uses REAL synthetic video clips generated by ffmpeg (not mocks). This
genuinely exercises the extract → concat → mux pipeline. If ffmpeg is
missing, tests skip (not fail).
"""

import shutil
import sys
from pathlib import Path

import pytest

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
from videogen.edl import EDL, EDL_SCHEMA_VERSION, Shot, Provenance, Transition  # noqa: E402
from videogen.timeline import VOSegment, ClipAssignment, build_edl  # noqa: E402
from videogen.render import render_video  # noqa: E402

# Skip all if ffmpeg missing
pytestmark = pytest.mark.skipif(
    shutil.which("ffmpeg") is None, reason="ffmpeg not available"
)


# --- fixtures ----------------------------------------------------------------

def _make_synthetic_clip(path: Path, duration: float = 10.0, w: int = 320, h: int = 240):
    """Generate a real test-pattern video clip via ffmpeg lavfi."""
    import subprocess
    subprocess.run([
        "ffmpeg", "-y", "-hide_banner", "-loglevel", "error",
        "-f", "lavfi",
        "-i", f"testsrc=duration={duration}:size={w}x{h}:rate=30",
        "-c:v", "libx264",
        "-pix_fmt", "yuv420p",
        str(path),
    ], check=True, timeout=30)


def _make_silence_mp3(path: Path, duration: float = 5.0):
    """Generate a silent MP3 of given duration."""
    import subprocess
    subprocess.run([
        "ffmpeg", "-y", "-hide_banner", "-loglevel", "error",
        "-f", "lavfi",
        "-i", f"anullsrc=channel_layout=mono:sample_rate=32000",
        "-t", str(duration),
        "-c:a", "libmp3lame",
        str(path),
    ], check=True, timeout=30)


@pytest.fixture
def synthetic_clips(tmp_path):
    """Create 3 synthetic clips + VO segments + a valid EDL."""
    clips_dir = tmp_path / "clips"
    clips_dir.mkdir()
    vo_dir = tmp_path / "vo"
    vo_dir.mkdir()

    # 3 clips, each 12s (enough handle for 10s shots)
    shot_data = [
        ("shot1", 10.0),
        ("shot2", 8.0),
        ("shot3", 6.0),
    ]

    vo_segments = []
    clip_assignments = []

    for shot_id, dur in shot_data:
        clip_path = clips_dir / f"{shot_id}.mp4"
        _make_synthetic_clip(clip_path, duration=dur + 2.0)

        vo_path = vo_dir / f"{shot_id}.mp3"
        _make_silence_mp3(vo_path, duration=dur)

        vo_segments.append(VOSegment(
            shot_id=shot_id, text=f"Subtitle for {shot_id}",
            mp3_path=str(vo_path), duration_sec=dur,
        ))
        clip_assignments.append(ClipAssignment(
            shot_id=shot_id, source_path=str(clip_path),
            clip_start_sec=0.0, clip_end_sec=dur + 2.0,
            provenance=Provenance(
                source="pexels", asset_id=shot_id,
                licence="Pexels", authenticity="stock",
            ),
        ))

    edl = build_edl(vo_segments, clip_assignments, tour="test-render")
    return edl, tmp_path


# --- extract + concat tests --------------------------------------------------

class TestRenderVideo:
    def test_renders_valid_mp4(self, synthetic_clips):
        """render_video produces a real, playable MP4."""
        edl, tmp_path = synthetic_clips
        result = render_video(edl, tmp_path / "work")
        assert Path(result.video_path).exists()
        assert result.video_path.endswith(".mp4")

    def test_duration_matches_edl(self, synthetic_clips):
        """The rendered video's duration should match the EDL total (±1s for encoding)."""
        edl, tmp_path = synthetic_clips
        result = render_video(edl, tmp_path / "work")
        assert abs(result.duration_sec - edl.total_duration_sec) < 2.0

    def test_has_video_stream(self, synthetic_clips):
        """The output has a valid h264 video stream."""
        edl, tmp_path = synthetic_clips
        result = render_video(edl, tmp_path / "work")
        assert "264" in result.codec or "h264" in result.codec

    def test_has_audio_from_vo(self, synthetic_clips):
        """When VO segments exist in work_dir/vo/, audio is muxed in."""
        import subprocess, json
        edl, tmp_path = synthetic_clips
        # Copy VO segments into the work dir where render_video expects them
        work_dir = tmp_path / "work"
        work_vo_dir = work_dir / "vo"
        work_vo_dir.mkdir(parents=True, exist_ok=True)
        for vo_file in (tmp_path / "vo").glob("*.mp3"):
            shutil.copy2(vo_file, work_vo_dir)
        result = render_video(edl, work_dir)
        probe = subprocess.run(
            ["ffprobe", "-v", "quiet", "-show_streams", "-of", "json", result.video_path],
            capture_output=True, text=True, check=True,
        )
        streams = json.loads(probe.stdout).get("streams", [])
        audio_streams = [s for s in streams if s.get("codec_type") == "audio"]
        assert len(audio_streams) >= 1, "Expected audio track from VO segments"

    def test_resolution_scaled(self, synthetic_clips):
        """Output is scaled to 1920x1080 (default)."""
        edl, tmp_path = synthetic_clips
        result = render_video(edl, tmp_path / "work")
        assert "1920" in result.resolution

    def test_shot_count_in_segments(self, synthetic_clips):
        """Each EDL shot produces one extracted segment."""
        edl, tmp_path = synthetic_clips
        render_video(edl, tmp_path / "work")
        segments = list((tmp_path / "work" / "segments").glob("*.mp4"))
        assert len(segments) == 3

    def test_empty_edl_raises(self, tmp_path):
        """Rendering an empty EDL should raise, not produce garbage."""
        edl = EDL(schema_version=EDL_SCHEMA_VERSION, tour="empty", total_duration_sec=0, edl=[])
        with pytest.raises(ValueError, match="empty"):
            render_video(edl, tmp_path / "work")


class TestRenderWithExternalAudio:
    def test_external_audio_muxed(self, synthetic_clips):
        """When audio_path is provided, it's muxed onto the video."""
        edl, tmp_path = synthetic_clips
        # Create a synthetic mixed audio track
        audio_path = tmp_path / "mixed.mp3"
        _make_silence_mp3(audio_path, duration=edl.total_duration_sec)
        result = render_video(edl, tmp_path / "work", audio_path=str(audio_path))
        assert Path(result.video_path).exists()


class TestRenderSingleShot:
    def test_single_shot_renders(self, tmp_path):
        """A one-shot EDL should render correctly."""
        clip_path = tmp_path / "only.mp4"
        _make_synthetic_clip(clip_path, duration=12.0)
        vo_path = tmp_path / "vo" / "shot1.mp3"
        vo_path.parent.mkdir(exist_ok=True)
        _make_silence_mp3(vo_path, duration=10.0)

        vo = [VOSegment(shot_id="shot1", text="Only shot",
                        mp3_path=str(vo_path), duration_sec=10.0)]
        clips = [ClipAssignment(shot_id="shot1", source_path=str(clip_path),
                                clip_start_sec=0, clip_end_sec=12,
                                provenance=Provenance(source="company_owned",
                                asset_id="1", licence="Commercial",
                                authenticity="documentary"))]
        edl = build_edl(vo, clips, tour="single")
        result = render_video(edl, tmp_path / "work")
        assert abs(result.duration_sec - 10.0) < 2.0
