"""
Pydantic v2 Models — 嚴格校驗 LLM Output

LLM 嘅 JSON output 唔可信（漏欄、類型錯、幻覺），
所有 LLM output 必須過呢度嘅 strict schema parse。
"""

from datetime import datetime
from typing import List, Optional, Literal

from pydantic import BaseModel, Field, field_validator, ConfigDict


# ===== 觸發類型 / 領域列舉（同 specs/seed-package-schema-v1.md 一致）=====
TRIGGER_TYPES = Literal[
    "aesthetic_gaze", "anomaly_detection",
    "professional_judgment", "manual", "other",
]
DOMAINS = Literal[
    "tourism", "legal", "medical",
    "industrial", "education", "other",
]


# ===== Raw Data（來自 Inbox JSON）=====
class RawData(BaseModel):
    """硬件 / App 採集嘅原始觸發數據。

    GPS 用巢狀結構 gps:{lat,lng} —— 同 specs/api-protocol-v1.md §4
    同 tools/seed_generator/generate_seed.py 嘅輸入契約一致。
    """

    model_config = ConfigDict(extra="ignore")

    timestamp: str
    gps: dict  # {"lat": float, "lng": float}
    trigger_type: TRIGGER_TYPES
    domain: DOMAINS
    human_description: str
    human_label: Optional[str] = None
    tags: List[str] = Field(default_factory=list)
    hardware: Optional[str] = None
    trigger_duration: Optional[float] = Field(None, ge=0)

    @field_validator("timestamp")
    @classmethod
    def validate_timestamp(cls, v: str) -> str:
        """ISO 8601 基本校驗。"""
        try:
            datetime.fromisoformat(v.replace("Z", "+00:00"))
        except ValueError as e:
            raise ValueError(f"Invalid timestamp format: {v}") from e
        return v

    @field_validator("gps")
    @classmethod
    def validate_gps(cls, v: dict) -> dict:
        if "lat" not in v or "lng" not in v:
            raise ValueError("gps must contain 'lat' and 'lng'")
        if not (-90 <= float(v["lat"]) <= 90):
            raise ValueError("gps.lat out of range [-90, 90]")
        if not (-180 <= float(v["lng"]) <= 180):
            raise ValueError("gps.lng out of range [-180, 180]")
        return v

    @property
    def gps_lat(self) -> float:
        return float(self.gps["lat"])

    @property
    def gps_lng(self) -> float:
        return float(self.gps["lng"])


# ===== Draft Entry（Generator 產出）=====
class DraftEntry(BaseModel):
    """LLM generator 產出嘅草稿。"""

    frontmatter: dict
    body_human_description: str
    body_ai_analysis: str
    body_related_links: List[str] = Field(default_factory=list)


# ===== Audit Result（Auditor 產出）=====
class AuditResult(BaseModel):
    """DeepSeek auditor 嘅審查結果。"""

    verdict: Literal["pass", "fail"]
    issues: List[str] = Field(default_factory=list)
    corrected: Optional[DraftEntry] = None  # verdict=fail 時可選嘅修正版


# ===== Final Entry（Engine 最終產出）=====
class FinalEntry(BaseModel):
    """入庫前嘅最終 entry，可序列化為對齊 P0 generate_seed.py 嘅 Markdown。"""

    frontmatter: dict
    body_human_description: str
    body_ai_analysis: str
    body_related_links: List[str] = Field(default_factory=list)

    audited: bool = False
    audited_corrected: bool = False
    audit_log: Optional[str] = None

    # 用嚟衍生輸出檔名（cli.py 用）
    raw_timestamp: str = ""
    raw_domain: str = "other"

    def to_markdown(self) -> str:
        """
        輸出 Markdown，格式 1:1 對齊 tools/seed_generator/generate_seed.py
        嘅 create_entry() —— 咁 validate_seed.py 同 vault 結構先兼容。

        🔒 關鍵：timestamp 必須加引號，否則 YAML 會 parse 做 datetime
        object，令 validate_seed 報「timestamp 必須係 string」
        （P0 已踩過呢個坑，唔可以再犯）。
        """
        fm = self.frontmatter
        ts = fm.get("timestamp", self.raw_timestamp)
        gps_lat = fm.get("gps_lat", 0)
        gps_lng = fm.get("gps_lng", 0)
        trigger_type = fm.get("trigger_type", "manual")
        domain = fm.get("domain", self.raw_domain)
        tags = fm.get("tags", "")
        if isinstance(tags, list):
            tags = ", ".join(tags)
        human_label = fm.get("human_label", "")

        lines = [
            "---",
            f'timestamp: "{ts}"',  # 🔒 引號！
            f"gps_lat: {gps_lat}",
            f"gps_lng: {gps_lng}",
            f"trigger_type: {trigger_type}",
            f"domain: {domain}",
            f"tags: {tags}",
            f"human_label: {human_label}",
            "---",
            "",
            "## Human Description",
            self.body_human_description,
            "",
            "## AI Analysis",
            self.body_ai_analysis,
            "",
            "## Related Links",
        ]
        if self.body_related_links:
            for link in self.body_related_links:
                lines.append(f"- {link}")
        else:
            lines.append("<!-- Auto-generated bidirectional links -->")

        # Audit 標記（修正過嘅 entry 留 audit_log）
        if self.audited_corrected and self.audit_log:
            lines.extend(["", f"<!-- audit_log: {self.audit_log} -->"])

        lines.extend([
            "",
            "---",
            "*Generated by Goldman Global Hive.AGI LLM Wiki Engine v1.0*",
        ])
        return "\n".join(lines)
