#!/usr/bin/env python3
"""
Seed Package Generator v1.0
將 Raw Data 轉為標準化 Seed Package
"""

import json
import os
from datetime import datetime
from pathlib import Path


class SeedGenerator:
    def __init__(self, output_dir="./seed_output"):
        self.output_dir = Path(output_dir)
        self.output_dir.mkdir(exist_ok=True)

    def create_entry(self, data):
        """將單一 Raw Data 轉為 Markdown Entry"""
        timestamp = data.get('timestamp', datetime.now().isoformat())
        gps = data.get('gps', {})
        trigger_type = data.get('trigger_type', 'manual')
        human_label = data.get('human_label', '')
        human_description = data.get('human_description', '')
        domain = data.get('domain', 'tourism')
        tags = data.get('tags', [])

        md_content = f"""---
timestamp: "{timestamp}"
gps_lat: {gps.get('lat', 0)}
gps_lng: {gps.get('lng', 0)}
trigger_type: {trigger_type}
domain: {domain}
tags: {', '.join(tags)}
human_label: {human_label}
---

## Human Description
{human_description}

## AI Analysis
<!-- LLM Wiki will auto-generate this section -->

## Related Links
<!-- Auto-generated bidirectional links -->

---
*Generated by Goldman Global Hive.AGI Seed Generator v1.0*
"""
        return md_content

    def generate_manifest(self, entries, contributor_id="goldman_global_lab"):
        """Generate manifest.json"""
        manifest = {
            "schema_version": "1.0",
            "contributor_id": contributor_id,
            "contributor_type": "organization",
            "created_at": datetime.now().isoformat(),
            "total_entries": len(entries),
            "domains": list(set(e.get('domain', 'other') for e in entries)),
            "language": "en",
            "geo_regions": ["AU-NSW"],
            "license": "CC-BY-NC-SA-4.0",
            "description": "Goldman Global human-perspective data collection program — first Seed Package batch",
            "contact": "cto@goldmanglobal.com.au"
        }
        return manifest

    def generate_seed_package(self, entries, package_name="seed_001"):
        """Generate a complete Seed Package"""
        package_dir = self.output_dir / package_name
        package_dir.mkdir(exist_ok=True)

        entries_dir = package_dir / "entries"
        entries_dir.mkdir(exist_ok=True)

        for i, entry_data in enumerate(entries, 1):
            md_content = self.create_entry(entry_data)
            with open(entries_dir / f"entry_{i:03d}.md", "w", encoding="utf-8") as f:
                f.write(md_content)

        manifest = self.generate_manifest(entries)
        with open(package_dir / "manifest.json", "w", encoding="utf-8") as f:
            json.dump(manifest, f, indent=2, ensure_ascii=False)

        with open(package_dir / "README.md", "w", encoding="utf-8") as f:
            f.write(f"""# Seed Package: {package_name}

**Contributor**: Goldman Global Research Lab
**Created**: {datetime.now().isoformat()}
**Entry count**: {len(entries)}
**Domains**: {', '.join(set(e.get('domain', 'other') for e in entries))}

## Usage
1. Place this folder into your Obsidian Vault `/03_SeedPackages/`
2. Run the LLM Wiki Engine to fuse knowledge

## Contact
cto@goldmanglobal.com.au
""")

        print(f"✅ Seed Package generated: {package_dir}")
        return package_dir


# ===== 使用範例 =====
if __name__ == "__main__":
    sample_entries = [
        {
            "timestamp": "2026-07-25T19:30:00Z",
            "gps": {"lat": -33.8568, "lng": 151.2153},
            "trigger_type": "aesthetic_gaze",
            "domain": "tourism",
            "human_label": "beautiful",
            "human_description": "Sunset light pouring through the gaps between shipping containers, forming golden shafts of light. A dialogue between industry and nature.",
            "tags": ["sunset", "container-terminal", "golden-hour"]
        },
        {
            "timestamp": "2026-07-25T20:00:00Z",
            "gps": {"lat": -33.8572, "lng": 151.2145},
            "trigger_type": "aesthetic_gaze",
            "domain": "tourism",
            "human_label": "beautiful",
            "human_description": "Opera House lights at night reflected on the harbour; the rippling water turns the reflection into shattered gold.",
            "tags": ["opera-house", "night-scene", "reflection"]
        }
    ]

    generator = SeedGenerator()
    generator.generate_seed_package(sample_entries, "seed_goldman_20260725")
