#!/usr/bin/env python3
"""
Seed Package Generator v1.0
將 Raw Data 轉為標準化 Seed Package
"""

import json
import os
from datetime import datetime
from pathlib import Path


class SeedGenerator:
    def __init__(self, output_dir="./seed_output"):
        self.output_dir = Path(output_dir)
        self.output_dir.mkdir(exist_ok=True)

    def create_entry(self, data):
        """將單一 Raw Data 轉為 Markdown Entry"""
        timestamp = data.get('timestamp', datetime.now().isoformat())
        gps = data.get('gps', {})
        trigger_type = data.get('trigger_type', 'manual')
        human_label = data.get('human_label', '')
        human_description = data.get('human_description', '')
        domain = data.get('domain', 'tourism')
        tags = data.get('tags', [])

        md_content = f"""---
timestamp: "{timestamp}"
gps_lat: {gps.get('lat', 0)}
gps_lng: {gps.get('lng', 0)}
trigger_type: {trigger_type}
domain: {domain}
tags: {', '.join(tags)}
human_label: {human_label}
---

## 人類描述
{human_description}

## AI 分析
<!-- LLM Wiki 將自動生成此部分 -->

## 相關鏈接
<!-- 自動生成嘅雙向鏈接 -->

---
*Generated by Goldman Global Hive.AGI Seed Generator v1.0*
"""
        return md_content

    def generate_manifest(self, entries, contributor_id="goldman_global_lab"):
        """生成 manifest.json"""
        manifest = {
            "schema_version": "1.0",
            "contributor_id": contributor_id,
            "contributor_type": "organization",
            "created_at": datetime.now().isoformat(),
            "total_entries": len(entries),
            "domains": list(set(e.get('domain', 'other') for e in entries)),
            "language": "zh-HK",
            "geo_regions": ["AU-NSW"],
            "license": "CC-BY-NC-SA-4.0",
            "description": "Goldman Global 人類視角數據採集計劃 — 第一批 Seed Package",
            "contact": "cto@goldmanglobal.com.au"
        }
        return manifest

    def generate_seed_package(self, entries, package_name="seed_001"):
        """生成完整 Seed Package"""
        package_dir = self.output_dir / package_name
        package_dir.mkdir(exist_ok=True)

        entries_dir = package_dir / "entries"
        entries_dir.mkdir(exist_ok=True)

        for i, entry_data in enumerate(entries, 1):
            md_content = self.create_entry(entry_data)
            with open(entries_dir / f"entry_{i:03d}.md", "w", encoding="utf-8") as f:
                f.write(md_content)

        manifest = self.generate_manifest(entries)
        with open(package_dir / "manifest.json", "w", encoding="utf-8") as f:
            json.dump(manifest, f, indent=2, ensure_ascii=False)

        with open(package_dir / "README.md", "w", encoding="utf-8") as f:
            f.write(f"""# Seed Package: {package_name}

**貢獻者**: Goldman Global Research Lab
**建立日期**: {datetime.now().isoformat()}
**Entry 數量**: {len(entries)}
**領域**: {', '.join(set(e.get('domain', 'other') for e in entries))}

## 使用說明
1. 將呢個 Folder 放入你嘅 Obsidian Vault `/03_SeedPackages/`
2. 運行 LLM Wiki Engine 進行知識融合

## 聯絡
cto@goldmanglobal.com.au
""")

        print(f"✅ Seed Package 已生成: {package_dir}")
        return package_dir


# ===== 使用範例 =====
if __name__ == "__main__":
    sample_entries = [
        {
            "timestamp": "2026-07-25T19:30:00Z",
            "gps": {"lat": -33.8568, "lng": 151.2153},
            "trigger_type": "aesthetic_gaze",
            "domain": "tourism",
            "human_label": "靚",
            "human_description": "夕陽穿過貨櫃之間嘅縫隙，形成金色光柱。工業與自然對話嘅感覺。",
            "tags": ["日落", "貨櫃碼頭", "黃金時刻"]
        },
        {
            "timestamp": "2026-07-25T20:00:00Z",
            "gps": {"lat": -33.8572, "lng": 151.2145},
            "trigger_type": "aesthetic_gaze",
            "domain": "tourism",
            "human_label": "靚",
            "human_description": "歌劇院夜晚燈光倒映喺海面，水面波動令燈光變成碎金。",
            "tags": ["歌劇院", "夜景", "倒影"]
        }
    ]

    generator = SeedGenerator()
    generator.generate_seed_package(sample_entries, "seed_goldman_20260725")
