#!/usr/bin/env python3
"""
Obsidian Vault Setup v1.0
自動建立 Hive.AGI 嘅 Obsidian Vault 目錄結構、Templates、_SCHEMA.md、_README.md

用法:
    python setup_vault.py                       # 預設 ./HiveAGI_Vault
    python setup_vault.py --target ~/HiveAGI    # 自訂路徑
"""

import argparse
import shutil
from pathlib import Path


# Vault 目錄結構（對應 specs/vault-structure-spec.md）
VAULT_DIRS = [
    "00_Inbox",
    "01_Entries",
    "02_Topics",
    "03_SeedPackages",
    "04_Templates",
    "99_Archive",
]

SCHEMA_MD = """# Hive.AGI Vault — Schema

> This Vault follows the Project Hive.AGI structure specification.
> See the repo `specs/vault-structure-spec.md` for the full spec.

## Directory purposes

| Directory | Purpose |
| :--- | :--- |
| `00_Inbox/` | Staging area for Raw Data (JSON) collected by hardware / apps |
| `01_Entries/` | Standardized Markdown notes generated by the LLM Wiki Engine |
| `02_Topics/` | MOC (Map of Content), aggregated by domain |
| `03_SeedPackages/` | Exported Seed Packages (exchangeable) |
| `04_Templates/` | Obsidian Templates |
| `99_Archive/` | Archive for old notes |

## Naming conventions

- Inbox JSON: `YYYY-MM-DD_HHMM_Location.json`
- Entry Markdown: `YYYY-MM-DD_Location_Subject.md`
- MOC: `_MOC_Domain.md`
- Seed Package Folder: `seed_contributor_YYYYMMDD_vX/`

## Bidirectional links

- Use `[[Page Name]]`
- Each Entry links to at least one MOC

## License

- Code: AGPL-3.0
- Seed Data: CC-BY-NC-SA-4.0

Contact: cto@goldmanglobal.com.au
"""

VAULT_README = """# Hive.AGI Vault

This is your Project Hive.AGI Obsidian Vault.

## Quick start

1. Open this folder as a Vault in Obsidian
2. Put Raw Data into `00_Inbox/`
3. (P1) Run the LLM Wiki Engine to generate notes into `01_Entries/`
4. Use the Seed Generator to produce a Seed Package into `03_SeedPackages/`

## Structure

See `_SCHEMA.md`.

## Contact

cto@goldmanglobal.com.au
"""

# 04_Templates 入面嘅 seed MOC 種子檔
SEED_MOCS = {
    "_MOC_Tourism.md": """# 🗺️ MOC — Tourism

- [[]]
""",
    "_MOC_Industrial.md": """# 🗺️ MOC — Industrial

- [[]]
""",
    "_MOC_Legal.md": """# 🗺️ MOC — Legal

- [[]]
""",
}


def setup_vault(target):
    vault = Path(target).expanduser().resolve()
    vault.mkdir(parents=True, exist_ok=True)

    print(f"🔧 Creating Vault at: {vault}")

    # 1. 目錄
    for d in VAULT_DIRS:
        (vault / d).mkdir(exist_ok=True)
        print(f"  📁 {d}/")

    # 2. Templates（由 repo templates/ 複製；若搵唔到就用內建）
    templates_src = Path(__file__).parent / "templates"
    templates_dst = vault / "04_Templates"
    if templates_src.is_dir():
        for tpl in templates_src.glob("*.md"):
            shutil.copy2(tpl, templates_dst / tpl.name)
            print(f"  📄 04_Templates/{tpl.name} (copied)")
    else:
        # fallback：寫一個最細 entry template
        (templates_dst / "entry_template.md").write_text(
            "---\ntimestamp: \ngps_lat: \ngps_lng: \ntrigger_type: manual\n"
            "domain: other\ntags: \nhuman_label: \n---\n\n## Human Description\n\n",
            encoding="utf-8",
        )
        print("  📄 04_Templates/entry_template.md (fallback)")

    # 3. Seed MOCs
    topics = vault / "02_Topics"
    for name, content in SEED_MOCS.items():
        (topics / name).write_text(content, encoding="utf-8")
        print(f"  📄 02_Topics/{name}")

    # 4. _SCHEMA.md 同 _README.md
    (vault / "_SCHEMA.md").write_text(SCHEMA_MD, encoding="utf-8")
    print("  📄 _SCHEMA.md")
    (vault / "_README.md").write_text(VAULT_README, encoding="utf-8")
    print("  📄 _README.md")

    # 5. .gitkeep 俾空目錄可以入 git
    for d in VAULT_DIRS:
        gk = vault / d / ".gitkeep"
        if not any(gk.parent.iterdir()):
            gk.touch()

    print()
    print(f"✅ Vault created! Open it in Obsidian: {vault}")
    print(f"   Next step: put Raw Data into {vault / '00_Inbox'}/")


def main():
    parser = argparse.ArgumentParser(description="Create a Hive.AGI Obsidian Vault")
    parser.add_argument(
        "--target", default="./HiveAGI_Vault",
        help="Vault target path (default ./HiveAGI_Vault)"
    )
    args = parser.parse_args()
    setup_vault(args.target)


if __name__ == "__main__":
    main()
